name: openai
description: An OpenAI client.
dependencies:
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.10.0
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.9.0
